# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('hostname', models.CharField(max_length=80)),
                ('landscape', models.BooleanField(default=True)),
            ],
        ),
    ]
